"""Add pitcher_name to PitchAnalysis table

Revision ID: f999d63c2202
Revises: 
Create Date: 2025-07-02 13:57:54.250893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f999d63c2202'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_analyses', sa.Column('pitcher_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch_analyses', 'pitcher_name')
    # ### end Alembic commands ###
